In [36]:
import numpy as np

- numpy provide efficient storage 
- it also provide better way of handling data for procerssor 

In [37]:
myarr = np.array([[3,6,5,12]], np.int64)

In [38]:
myarr[0, 1]

np.int64(6)

In [39]:
myarr.shape

(1, 4)

In [40]:
myarr.dtype

dtype('int64')

In [41]:
myarr[0,1]= 45
myarr

array([[ 3, 45,  5, 12]])

In [42]:
listarray = np.array([[1,2,3,4],[5,66,7,8],[11,12,13,14]])
listarray

array([[ 1,  2,  3,  4],
       [ 5, 66,  7,  8],
       [11, 12, 13, 14]])

In [43]:
listarray.dtype

dtype('int64')

In [44]:
listarray.shape

(3, 4)

In [45]:
listarray.size

12

In [46]:
np.array({34,23,45})

array({34, 45, 23}, dtype=object)

In [47]:
zeros =np.zeros((2,5))
zeros


array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [48]:
ran= np.arange(15)
print(ran)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [49]:
space = np.linspace(1,5,5)
print(space)

[1. 2. 3. 4. 5.]


In [50]:
emp = np.empty((4,6))
emp

array([[6.23042070e-307, 4.67296746e-307, 1.69121096e-306,
        2.22520559e-306, 1.29060531e-306, 8.45599366e-307],
       [7.56593017e-307, 1.11258854e-306, 1.11261502e-306,
        1.42410839e-306, 7.56597770e-307, 6.23059726e-307],
       [1.42419530e-306, 1.11261027e-306, 6.89805151e-307,
        7.56592338e-307, 6.89807188e-307, 1.95819401e-306],
       [1.11261502e-306, 8.45559303e-307, 1.06811422e-306,
        1.05694828e-307, 1.42410974e-306, 8.45528067e-307]])

In [51]:
emp.shape

(4, 6)

In [52]:
emp.size

24

In [53]:
arr = np.arange(99)
arr = arr.reshape(3, 33)
print(arr)

[[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
  24 25 26 27 28 29 30 31 32]
 [33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56
  57 58 59 60 61 62 63 64 65]
 [66 67 68 69 70 71 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89
  90 91 92 93 94 95 96 97 98]]


In [54]:
zeros = np.zeros(10)
ones = np.ones(10)
print(zeros)
print(ones)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [55]:
list_array = np.array([[0,1,2],[3,4,5],[6,7,8]])
print(list_array)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [56]:
matrix = np.arange(9).reshape((3, 3))
print(matrix)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [57]:
matrix[::-1]

array([[6, 7, 8],
       [3, 4, 5],
       [0, 1, 2]])

In [58]:
matrix.sort

<function ndarray.sort>

In [59]:
# Create a random array
arr = np.random.randint(0, 20, size=15)
print("Original array:", arr)

# Extract odd numbers
odd_numbers = arr[arr % 2 != 0]
print("Odd numbers:", odd_numbers)


Original array: [13 10 10  0 16  1 18 17  6 10 15 12  2  0 18]
Odd numbers: [13  1 17 15]


In [60]:
even_numbers = matrix[matrix % 2 ==0]
print(even_numbers)

[0 2 4 6 8]


In [61]:
sum_all_elements = matrix.sum()
print(sum_all_elements)

36


In [62]:
sum_all_elements =matrix.mean()
print(sum_all_elements)


4.0


In [63]:
fvarray = np.random.randint(1,50,size=(5,5))
print(fvarray)

[[25 42 18 36 12]
 [10 15  4 10 20]
 [26 34 33 49 44]
 [39 14 10 18 28]
 [45 40 45 24 18]]


In [64]:
maxnum =fvarray.max()
print(maxnum)
minnum = fvarray.min()
print(minnum)

49
4


In [65]:
ddarr = np.random.randint((1,10),size=2)
print(ddarr)

[0 9]


In [66]:
# Create a 5x5 2D array
arr = np.zeros((4,4))

# Set the border elements to 1
arr[0, :] = 1
arr[-1, :] = 1
arr[:, 0] = 1
arr[:, -1] = 1

print(arr)


[[1. 1. 1. 1.]
 [1. 0. 0. 1.]
 [1. 0. 0. 1.]
 [1. 1. 1. 1.]]


In [67]:
matrix1 = np.random.randint(10,40 ,size=(4,4))
matrix2 = np.random.randint(10,50 ,size=(4,4))
print(matrix1)
print(matrix2)
Mul_two__matrixes =np.dot(matrix1,matrix2)
print(Mul_two__matrixes)

[[31 17 14 23]
 [28 27 22 25]
 [30 23 30 23]
 [10 25 28 38]]
[[15 32 32 33]
 [10 15 26 38]
 [34 35 30 45]
 [35 48 41 35]]
[[1916 2841 2797 3104]
 [2313 3271 3283 3815]
 [2505 3459 3401 4019]
 [2682 3499 3368 3870]]


In [68]:
np.extract(arr[::-1],matrix2)

array([15, 32, 32, 33, 10, 38, 34, 45, 35, 48, 41, 35], dtype=int32)

In [69]:
np.extract(arr[arr % 2 ==0],matrix1)

array([], dtype=int32)

In [70]:
matrix1*matrix2

array([[ 465,  544,  448,  759],
       [ 280,  405,  572,  950],
       [1020,  805,  900, 1035],
       [ 350, 1200, 1148, 1330]], dtype=int32)

In [76]:
a = np.array([[1,2,3],[4,5,6]])
print(a)

[[1 2 3]
 [4 5 6]]


In [77]:
# get a dimension 
a.ndim

2

In [78]:
# get a shape 
a.shape

(2, 3)

In [79]:
# get type 
a.dtype

dtype('int64')

In [81]:
# get size
a.size
a.itemsize

8

In [103]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [88]:
# get a specific element [r,c]
a[1,-2]

np.int64(13)

In [89]:
# get specfic row 
a[0,:]

array([1, 2, 3, 4, 5, 6, 7])

In [92]:
# get specific column
a[:,4]

array([ 5, 12])

In [95]:
# getting little more fancy[startindex:endindex:stepsize]
a[0,1:6:1]

array([2, 3, 4, 5, 6])

In [112]:
# replacing a number in array 
a[1,2]= 12
print(a)
# for specific column or row 
a[:,5]= [20,18]
print(a)


[[ 1  2  3  4  5 20  7]
 [ 8  9 12 11 12 20 14]]
[[ 1  2  3  4  5 20  7]
 [ 8  9 12 11 12 18 14]]


In [115]:
b= np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [128]:
# get specific element (work outside in )
b[0:,1:,1]

array([[4],
       [8]])

In [133]:
#replace 
b[:,1,:]= [[1,2],[6,9]]
b

array([[[1, 2],
        [1, 2]],

       [[5, 6],
        [6, 9]]])

## Initilization different types of Arrays

In [137]:
# all 0s matrixs 
np.zeros((4,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [138]:
# all ones matrixs 
np.ones((4,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [139]:
# any other number 
np.full((4,3),99)

array([[99, 99, 99],
       [99, 99, 99],
       [99, 99, 99],
       [99, 99, 99]])

In [140]:
# Any other number 
np.full_like(a,4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [142]:
# random decimal number 
np.random.random_sample(a.shape)

array([[0.43138282, 0.55462675, 0.04499851, 0.67969076, 0.96663454,
        0.62135513, 0.33105431],
       [0.13258987, 0.60289753, 0.17949135, 0.51889499, 0.77525549,
        0.09219306, 0.56291123]])

In [145]:
# random integer value 
np.random.randint(10,size=(4,3))

array([[9, 9, 9],
       [7, 8, 9],
       [9, 7, 3],
       [5, 7, 2]], dtype=int32)

In [147]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [152]:
arr =np.array([[1,2,3],[4,5,6]])
r1 = np.repeat(arr,3 ,axis=0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]
 [4 5 6]
 [4 5 6]
 [4 5 6]]


In [180]:
op=np.ones((5,5))
print(op)
z= np.zeros((3,3))
z[1,1] =9
print(z)
op[1:4,1:4] =z
print(op)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


### Mathmatics 

In [181]:
a = np.array([1,2,3,4,4,5])
print(a)

[1 2 3 4 4 5]


In [182]:
a+2

array([3, 4, 5, 6, 6, 7])

In [183]:
a-2

array([-1,  0,  1,  2,  2,  3])

In [184]:
a*2

array([ 2,  4,  6,  8,  8, 10])

In [185]:
a/2

array([0.5, 1. , 1.5, 2. , 2. , 2.5])

In [186]:
a**2

array([ 1,  4,  9, 16, 16, 25])